---
title: "Subgraphs: step by step"
output: html_notebook
---

http://rich-iannone.github.io/DiagrammeR/graphviz_and_mermaid.html

Here is a final example of a diagram created using R and RStudio information (obtained from the R.Version() and rstudioapi::versionInfo() functions). The output will of course vary by the system on which it was generated. Here is the output from the dev machine:

```{r}
library(DiagrammeR)

grViz("
digraph nicegraph {

    # graph, node, and edge definitions
    graph [compound = true, nodesep = .5, ranksep = .25, 
            color = crimson]
    
    node [fontname = Helvetica, fontcolor = darkslategray, 
            shape = rectangle, fixedsize = true, width = 1, 
            color = darkslategray]
    
    edge [color = grey, arrowhead = none, arrowtail = none]
    
    # subgraph for R information
    subgraph cluster0 {
        node [fixedsize = true, width = 3]
        '@@1-1' -> '@@1-2' -> '@@1-3' -> '@@1-4'
        '@@1-4' -> '@@1-5' -> '@@1-6' -> '@@1-7'
    }
    
    # subgraph for RStudio information
    subgraph cluster1 {
        node [fixedsize = true, width = 3]
        '@@2' -> '@@3'
    }
    
    Information             [width = 1.5]
    Information -> R
    Information -> RStudio
    R -> '@@1-1'            [lhead = cluster0]
    RStudio -> '@@2'        [lhead = cluster1]

}

[1]: paste0(names(R.Version())[1:7], ': ', R.Version()[1:7])
[2]: paste0('RStudio version:', rstudioapi::versionInfo()[[3]])
[3]: paste0('Current program mode: ', rstudioapi::versionInfo()[[2]])

")
```

### step 1: set up the boxes

```{r}
library(DiagrammeR)

grViz("
digraph nicegraph {

    # graph, node, and edge definitions
    graph [compound = true, nodesep = .5, ranksep = .25, 
            color = crimson]

    # set how the nodes and boxes will be presented            
    node [fontname = Helvetica, fontcolor = darkslategray, 
            shape = rectangle, fixedsize = true, width = 1, 
            color = darkslategray]            

    Information             [width = 1.5]
    Information -> R
    Information -> RStudio

}

")

```


### step #2: add the subgraphs

```{r}
library(DiagrammeR)

grViz("
digraph nicegraph {

    # graph, node, and edge definitions
    graph [compound = true, nodesep = .5, ranksep = .25, 
            color = crimson]
            
    Information             [width = 1.5]
    Information -> R
    Information -> RStudio
    

    # set how the nodes and boxes will be presented            
    node [fontname = Helvetica, fontcolor = darkslategray, 
            shape = rectangle, fixedsize = true, width = 1, 
            color = darkslategray]            
            
            
    # subgraph for R information
    subgraph cluster0 {
        node [fixedsize = true, width = 3]
        '@@1-1' -> '@@1-2' -> '@@1-3' -> '@@1-4'
        '@@1-4' -> '@@1-5' -> '@@1-6' -> '@@1-7'
    }
    
    # subgraph for RStudio information
    subgraph cluster1 {
        node [fixedsize = true, width = 3]
        '@@2' -> '@@3'
    }            



}

")

```

### step #3: add the variables

```{r}
library(DiagrammeR)

grViz("
digraph nicegraph {

    # step 1: add global definitions
    # graph, node, and edge definitions
    graph [compound = true, nodesep = .5, ranksep = .25, 
            color = crimson]

    # set how the nodes and boxes will be presented            
    node [fontname = Helvetica, fontcolor = darkslategray, 
            shape = rectangle, fixedsize = true, width = 1, 
            color = darkslategray]            
            
    
    Information             [width = 1.5]
    Information -> R
    Information -> RStudio
    
    # step 2: add subgraphs
            
    # subgraph for R information
    subgraph cluster0 {
        node [fixedsize = true, width = 3]
        '@@1-1' -> '@@1-2' -> '@@1-3' -> '@@1-4'
        '@@1-4' -> '@@1-5' -> '@@1-6' -> '@@1-7'
    }
    
    # subgraph for RStudio information
    subgraph cluster1 {
        node [fixedsize = true, width = 3]
        '@@2' -> '@@3'
    }            
    
    
    # step 3: add the parameters
    R       -> '@@1-1'      [lhead = cluster0]
    RStudio -> '@@2'        [lhead = cluster1]

}

")
```

### step 4: add values

```{r}
library(DiagrammeR)

grViz("
digraph nicegraph {

    # step 1: add global definitions
    
    # graph, node, and edge definitions
    graph [compound = true, nodesep = .5, ranksep = .25, 
            color = crimson]

    # set how the nodes and boxes will be presented            
    node [fontname = Helvetica, fontcolor = darkslategray, 
            shape = rectangle, fixedsize = true, width = 1, 
            color = darkslategray]            
            
    
    Information             [width = 1.5]
    Information -> R
    Information -> RStudio
    
    
    # step 2: add subgraphs
            
    # subgraph for R information
    subgraph cluster0 {
        node [fixedsize = true, width = 3]
        '@@1-1' -> '@@1-2' -> '@@1-3' -> '@@1-4'
        '@@1-4' -> '@@1-5' -> '@@1-6' -> '@@1-7'
    }
    
    # subgraph for RStudio information
    subgraph cluster1 {
        node [fixedsize = true, width = 3]
        '@@2' -> '@@3'
    }            
    
    
    # step 3: add the parameters
    # 
    R       -> '@@1-1'      [lhead = cluster0]
    RStudio -> '@@2'        [lhead = cluster1]

}

# step 4: add values
#
[1]: paste0(names(R.Version())[1:7], ': ', R.Version()[1:7])
[2]: paste0('RStudio version:', rstudioapi::versionInfo()[[3]])
[3]: paste0('Current program mode: ', rstudioapi::versionInfo()[[2]])

")
```
